Clean up function declarations
Change incorrect and missing translation unit names.

Add declarations for definitions with no corresponding declaration.

Remove declarations with no corresponding definition.

Remove declarations not used outside their definition's translation unit.

Fixes: GCC warnings:

whowatch.c: In function ‘info_wdgt’:
whowatch.c:300:2: warning: implicit declaration of function ‘info_reg’ [-Wimplicit-function-declaration]
  info_reg(w);
  ^~~~~~~~

plist.c: In function ‘getprocbyname’:
plist.c:194:2: warning: implicit declaration of function ‘scr_crsr_jmp’ [-Wimplicit-function-declaration]
  scr_crsr_jmp(w, p->line);
  ^~~~~~~~~~~~

ulist.c: In function ‘user_search’:
ulist.c:268:2: warning: implicit declaration of function ‘scr_crsr_jmp’ [-Wimplicit-function-declaration]
  scr_crsr_jmp(w, u->line);
  ^~~~~~~~~~~~